modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/noobanidus/noobutil/issues"
license="MIT"
[[mods]]
modId="mysticalworld"
version="1.0"
displayName="Mystical World"
displayURL="https://google.com"
credits="None"
authors="Noobanidus"
description='''
Description.
'''